# Google Cloud Build configuration for skill-map app
# This builds the Docker image on Cloud Build (AMD64) and pushes to Artifact Registry

steps:
  # Build the Docker image on Cloud Build (AMD64 architecture)
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_APP_NAME}:$BUILD_ID",
        "-t",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_APP_NAME}:latest",
        "--platform",
        "linux/amd64",
        "./app",
      ]

  # Push the image with build ID tag to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_APP_NAME}:$BUILD_ID",
      ]

  # Push the latest tag to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_APP_NAME}:latest",
      ]

# Options for faster builds
options:
  machineType: "E2_HIGHCPU_8" # Use high-CPU machine for faster builds
  diskSizeGb: 100
  dynamic_substitutions: true

# Default substitutions - can be overridden when triggering build
substitutions:
  _REGION: "asia-northeast1"
  _REPOSITORY: "skill-map-repo"
  _APP_NAME: "skill-map"

# Build timeout (5 minutes should be enough for most Next.js apps)
timeout: 300s

# Tags for organization
tags:
  - "skill-map"
  - "nextjs"
  - "production"
